# Site
name: "Dat T Nguyen"
title: "Dat T Nguyen"
description: "Where Dat's stories are collected..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://datnt.us7.list-manage.com/subscribe?u=3be95e9ff8d5d4544fc572811&id=53bec2da30'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dat:
    name: Dat
    display_name: Dat Thanh Nguyen
    gravatar: 4c10ff28fe545b751bc552248d938859
    email: n.dat@outlook.com
    web: https://dattn.com/
    twitter: https://twitter.com/ndatth_
    description: "Dat is a computational biologist, a data scientist specilized in medical science."
#   sal:
#     name: Sal
#     display_name: Sal
#     gravatar: e56154546cf4be74e393c62d1ae9f9d4
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net
#     twitter: https://twitter.com/wowthemesnet
#     description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
#   john:
#     name: John
#     display_name: John    
#     avatar: 'assets/images/avatar.png'
#     gravatar: b1cc14991db7a456fcd761680bbc8f81
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net
#     twitter: https://twitter.com/wowthemesnet
#     description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
